version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      #- ./backend/storage:/var/www/html/storage
    networks:
      - laravel
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel-app
      - DB_USERNAME=root
      - DB_PASSWORD=root

  webserver:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      #- ./backend:/app
      - ./backend:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - laravel
  #
  #db:
    #image: mysql:8.0
    #container_name: mysql
    #restart: unless-stopped
    #environment:
      #MYSQL_ROOT_PASSWORD: secret
      #MYSQL_DATABASE: laravel
      #MYSQL_USER: root
      #MYSQL_PASSWORD: secret
    #volumes:
      #- dbdata:/var/lib/mysql
    #networks:
      #- laravel
  
  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - ./mdbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - laravel
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    #restart: always
    ports:
      - 8081:80
  
  redis:
    image: redis
    ports:
      - 6379:6379 

networks:
  laravel:

volumes:
  dbdata:
